// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace File_Explorer
{
    static class Vsix
    {
        public const string Id = "0f53b279-3ac6-4152-9950-b2dd9dd3f80a";
        public const string Name = "File_Explorer";
        public const string Description = @"Locate and open files from Solution Explorer in File Explorer";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
